version: '3.7'

services:

  api:
   container_name: productapi
   build:
     context: .
     dockerfile: ./src/Product.Api/Dockerfile
   expose:
     - "8081"
   ports:
     - "5000:80"    
   depends_on:
     - postgres
     - rabbitmq
  
  worker:
   container_name: productworker
   build:
     context: .
     dockerfile: ./src/Product.Worker/Dockerfile    
   depends_on:
     - mongo-readonly
     - rabbitmq

  postgres:
    image: "postgres"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"  
    ports:
      - "5432:5432" 
      
  mongo-readonly:
    image: mongo:latest
    container_name: mongo-readonly 
    ports:
      - "27017:27017"       

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
        
  mongo:
    image: mongo:3 
    volumes:
      - ./mongo_data:/data/db
    networks:
      - graylog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog-network

  graylog:
    image: graylog/graylog:3.1.0
    volumes:
      - ./graylog_journal:/usr/share/graylog/data/journal
    environment:
      - TZ=America/Sao_Paulo
      - GRAYLOG_ROOT_TIMEZONE=America/Sao_Paulo
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - graylog-network
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

networks:
  graylog-network:
    external: false      