version: '3.7'

services:
  postgres:
    image: "postgres"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"  
    ports:
      - "5432:5432" 
      
  mongo:
    image: "mongo:latest"
    container_name: mongo 
    ports:
      - "27017:27017"       

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672